//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEscola
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aluno()
        {
            this.falta = new HashSet<falta>();
        }
    
        public string ra_aluno { get; set; }
        public string nm_aluno { get; set; }
        public string sb_aluno { get; set; }
        public Nullable<System.DateTime> dt_nascimento_aluno { get; set; }
        public string username { get; set; }
        public Nullable<int> cd_turma { get; set; }
    
        public virtual turma turma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<falta> falta { get; set; }
    }
}
