//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEscola
{
    using System;
    using System.Collections.Generic;
    
    public partial class auxiliar
    {
        public string cpf_auxiliar { get; set; }
        public string nm_auxiliar { get; set; }
        public string sb_auxiliar { get; set; }
        public Nullable<System.DateTime> dt_nascimento_auxiliar { get; set; }
        public Nullable<int> cd_categoria { get; set; }
    
        public virtual categoria_auxiliar categoria_auxiliar { get; set; }
    }
}
