//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEscola
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projetoescolaEntities : DbContext
    {
        public projetoescolaEntities()
            : base("name=projetoescolaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aluno> aluno { get; set; }
        public virtual DbSet<aluno_nota> aluno_nota { get; set; }
        public virtual DbSet<auxiliar> auxiliar { get; set; }
        public virtual DbSet<bimestre> bimestre { get; set; }
        public virtual DbSet<categoria_auxiliar> categoria_auxiliar { get; set; }
        public virtual DbSet<categoria_disciplina> categoria_disciplina { get; set; }
        public virtual DbSet<diretoria> diretoria { get; set; }
        public virtual DbSet<disciplina> disciplina { get; set; }
        public virtual DbSet<falta> falta { get; set; }
        public virtual DbSet<nivel_acesso> nivel_acesso { get; set; }
        public virtual DbSet<professor> professor { get; set; }
        public virtual DbSet<professor_disciplina> professor_disciplina { get; set; }
        public virtual DbSet<professor_turma> professor_turma { get; set; }
        public virtual DbSet<turma> turma { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
