//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEscola
{
    using System;
    using System.Collections.Generic;
    
    public partial class diretoria
    {
        public string cpf_direcao { get; set; }
        public string nm_direcao { get; set; }
        public string sb_direcao { get; set; }
        public Nullable<System.DateTime> dt_nascimento_direcao { get; set; }
        public string username { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
