//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoEscola
{
    using System;
    using System.Collections.Generic;
    
    public partial class professor_turma
    {
        public int cd_prof_turma { get; set; }
        public string cpf_professor { get; set; }
        public Nullable<int> cd_turma { get; set; }
    
        public virtual professor professor { get; set; }
        public virtual turma turma { get; set; }
    }
}
